/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactUsCountryRouteImport } from './routes/contact-us.$country'
import { Route as AuthClientRouteRouteImport } from './routes/_auth/client/route'
import { Route as AuthAdminRouteRouteImport } from './routes/_auth/admin/route'
import { Route as publicSearchRouteRouteImport } from './routes/(public)/search/route'
import { Route as publicCategoriesRouteRouteImport } from './routes/(public)/categories/route'
import { Route as ContactUsCountryCityRouteImport } from './routes/contact-us.$country.$city'
import { Route as publicCategoriesCategoryIdRouteRouteImport } from './routes/(public)/categories/$categoryId/route'
import { Route as publicCategoriesCategoryIdSubcategoryIdRouteRouteImport } from './routes/(public)/categories/$categoryId/$subcategoryId/route'
import { Route as publicCategoriesCategoryIdSubcategoryIdProductIdRouteRouteImport } from './routes/(public)/categories/$categoryId/$subcategoryId/$productId/route'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsCountryRoute = ContactUsCountryRouteImport.update({
  id: '/$country',
  path: '/$country',
  getParentRoute: () => ContactUsRoute,
} as any)
const AuthClientRouteRoute = AuthClientRouteRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminRouteRoute = AuthAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const publicSearchRouteRoute = publicSearchRouteRouteImport.update({
  id: '/(public)/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const publicCategoriesRouteRoute = publicCategoriesRouteRouteImport.update({
  id: '/(public)/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsCountryCityRoute = ContactUsCountryCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => ContactUsCountryRoute,
} as any)
const publicCategoriesCategoryIdRouteRoute =
  publicCategoriesCategoryIdRouteRouteImport.update({
    id: '/$categoryId',
    path: '/$categoryId',
    getParentRoute: () => publicCategoriesRouteRoute,
  } as any)
const publicCategoriesCategoryIdSubcategoryIdRouteRoute =
  publicCategoriesCategoryIdSubcategoryIdRouteRouteImport.update({
    id: '/$subcategoryId',
    path: '/$subcategoryId',
    getParentRoute: () => publicCategoriesCategoryIdRouteRoute,
  } as any)
const publicCategoriesCategoryIdSubcategoryIdProductIdRouteRoute =
  publicCategoriesCategoryIdSubcategoryIdProductIdRouteRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => publicCategoriesCategoryIdSubcategoryIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRouteWithChildren
  '/login': typeof LoginRoute
  '/categories': typeof publicCategoriesRouteRouteWithChildren
  '/search': typeof publicSearchRouteRoute
  '/admin': typeof AuthAdminRouteRoute
  '/client': typeof AuthClientRouteRoute
  '/contact-us/$country': typeof ContactUsCountryRouteWithChildren
  '/categories/$categoryId': typeof publicCategoriesCategoryIdRouteRouteWithChildren
  '/contact-us/$country/$city': typeof ContactUsCountryCityRoute
  '/categories/$categoryId/$subcategoryId': typeof publicCategoriesCategoryIdSubcategoryIdRouteRouteWithChildren
  '/categories/$categoryId/$subcategoryId/$productId': typeof publicCategoriesCategoryIdSubcategoryIdProductIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRouteWithChildren
  '/login': typeof LoginRoute
  '/categories': typeof publicCategoriesRouteRouteWithChildren
  '/search': typeof publicSearchRouteRoute
  '/admin': typeof AuthAdminRouteRoute
  '/client': typeof AuthClientRouteRoute
  '/contact-us/$country': typeof ContactUsCountryRouteWithChildren
  '/categories/$categoryId': typeof publicCategoriesCategoryIdRouteRouteWithChildren
  '/contact-us/$country/$city': typeof ContactUsCountryCityRoute
  '/categories/$categoryId/$subcategoryId': typeof publicCategoriesCategoryIdSubcategoryIdRouteRouteWithChildren
  '/categories/$categoryId/$subcategoryId/$productId': typeof publicCategoriesCategoryIdSubcategoryIdProductIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRouteWithChildren
  '/login': typeof LoginRoute
  '/(public)/categories': typeof publicCategoriesRouteRouteWithChildren
  '/(public)/search': typeof publicSearchRouteRoute
  '/_auth/admin': typeof AuthAdminRouteRoute
  '/_auth/client': typeof AuthClientRouteRoute
  '/contact-us/$country': typeof ContactUsCountryRouteWithChildren
  '/(public)/categories/$categoryId': typeof publicCategoriesCategoryIdRouteRouteWithChildren
  '/contact-us/$country/$city': typeof ContactUsCountryCityRoute
  '/(public)/categories/$categoryId/$subcategoryId': typeof publicCategoriesCategoryIdSubcategoryIdRouteRouteWithChildren
  '/(public)/categories/$categoryId/$subcategoryId/$productId': typeof publicCategoriesCategoryIdSubcategoryIdProductIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact-us'
    | '/login'
    | '/categories'
    | '/search'
    | '/admin'
    | '/client'
    | '/contact-us/$country'
    | '/categories/$categoryId'
    | '/contact-us/$country/$city'
    | '/categories/$categoryId/$subcategoryId'
    | '/categories/$categoryId/$subcategoryId/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact-us'
    | '/login'
    | '/categories'
    | '/search'
    | '/admin'
    | '/client'
    | '/contact-us/$country'
    | '/categories/$categoryId'
    | '/contact-us/$country/$city'
    | '/categories/$categoryId/$subcategoryId'
    | '/categories/$categoryId/$subcategoryId/$productId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/contact-us'
    | '/login'
    | '/(public)/categories'
    | '/(public)/search'
    | '/_auth/admin'
    | '/_auth/client'
    | '/contact-us/$country'
    | '/(public)/categories/$categoryId'
    | '/contact-us/$country/$city'
    | '/(public)/categories/$categoryId/$subcategoryId'
    | '/(public)/categories/$categoryId/$subcategoryId/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactUsRoute: typeof ContactUsRouteWithChildren
  LoginRoute: typeof LoginRoute
  publicCategoriesRouteRoute: typeof publicCategoriesRouteRouteWithChildren
  publicSearchRouteRoute: typeof publicSearchRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us/$country': {
      id: '/contact-us/$country'
      path: '/$country'
      fullPath: '/contact-us/$country'
      preLoaderRoute: typeof ContactUsCountryRouteImport
      parentRoute: typeof ContactUsRoute
    }
    '/_auth/client': {
      id: '/_auth/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof AuthClientRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(public)/search': {
      id: '/(public)/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof publicSearchRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/categories': {
      id: '/(public)/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof publicCategoriesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us/$country/$city': {
      id: '/contact-us/$country/$city'
      path: '/$city'
      fullPath: '/contact-us/$country/$city'
      preLoaderRoute: typeof ContactUsCountryCityRouteImport
      parentRoute: typeof ContactUsCountryRoute
    }
    '/(public)/categories/$categoryId': {
      id: '/(public)/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof publicCategoriesCategoryIdRouteRouteImport
      parentRoute: typeof publicCategoriesRouteRoute
    }
    '/(public)/categories/$categoryId/$subcategoryId': {
      id: '/(public)/categories/$categoryId/$subcategoryId'
      path: '/$subcategoryId'
      fullPath: '/categories/$categoryId/$subcategoryId'
      preLoaderRoute: typeof publicCategoriesCategoryIdSubcategoryIdRouteRouteImport
      parentRoute: typeof publicCategoriesCategoryIdRouteRoute
    }
    '/(public)/categories/$categoryId/$subcategoryId/$productId': {
      id: '/(public)/categories/$categoryId/$subcategoryId/$productId'
      path: '/$productId'
      fullPath: '/categories/$categoryId/$subcategoryId/$productId'
      preLoaderRoute: typeof publicCategoriesCategoryIdSubcategoryIdProductIdRouteRouteImport
      parentRoute: typeof publicCategoriesCategoryIdSubcategoryIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAdminRouteRoute: typeof AuthAdminRouteRoute
  AuthClientRouteRoute: typeof AuthClientRouteRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAdminRouteRoute: AuthAdminRouteRoute,
  AuthClientRouteRoute: AuthClientRouteRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ContactUsCountryRouteChildren {
  ContactUsCountryCityRoute: typeof ContactUsCountryCityRoute
}

const ContactUsCountryRouteChildren: ContactUsCountryRouteChildren = {
  ContactUsCountryCityRoute: ContactUsCountryCityRoute,
}

const ContactUsCountryRouteWithChildren =
  ContactUsCountryRoute._addFileChildren(ContactUsCountryRouteChildren)

interface ContactUsRouteChildren {
  ContactUsCountryRoute: typeof ContactUsCountryRouteWithChildren
}

const ContactUsRouteChildren: ContactUsRouteChildren = {
  ContactUsCountryRoute: ContactUsCountryRouteWithChildren,
}

const ContactUsRouteWithChildren = ContactUsRoute._addFileChildren(
  ContactUsRouteChildren,
)

interface publicCategoriesCategoryIdSubcategoryIdRouteRouteChildren {
  publicCategoriesCategoryIdSubcategoryIdProductIdRouteRoute: typeof publicCategoriesCategoryIdSubcategoryIdProductIdRouteRoute
}

const publicCategoriesCategoryIdSubcategoryIdRouteRouteChildren: publicCategoriesCategoryIdSubcategoryIdRouteRouteChildren =
  {
    publicCategoriesCategoryIdSubcategoryIdProductIdRouteRoute:
      publicCategoriesCategoryIdSubcategoryIdProductIdRouteRoute,
  }

const publicCategoriesCategoryIdSubcategoryIdRouteRouteWithChildren =
  publicCategoriesCategoryIdSubcategoryIdRouteRoute._addFileChildren(
    publicCategoriesCategoryIdSubcategoryIdRouteRouteChildren,
  )

interface publicCategoriesCategoryIdRouteRouteChildren {
  publicCategoriesCategoryIdSubcategoryIdRouteRoute: typeof publicCategoriesCategoryIdSubcategoryIdRouteRouteWithChildren
}

const publicCategoriesCategoryIdRouteRouteChildren: publicCategoriesCategoryIdRouteRouteChildren =
  {
    publicCategoriesCategoryIdSubcategoryIdRouteRoute:
      publicCategoriesCategoryIdSubcategoryIdRouteRouteWithChildren,
  }

const publicCategoriesCategoryIdRouteRouteWithChildren =
  publicCategoriesCategoryIdRouteRoute._addFileChildren(
    publicCategoriesCategoryIdRouteRouteChildren,
  )

interface publicCategoriesRouteRouteChildren {
  publicCategoriesCategoryIdRouteRoute: typeof publicCategoriesCategoryIdRouteRouteWithChildren
}

const publicCategoriesRouteRouteChildren: publicCategoriesRouteRouteChildren = {
  publicCategoriesCategoryIdRouteRoute:
    publicCategoriesCategoryIdRouteRouteWithChildren,
}

const publicCategoriesRouteRouteWithChildren =
  publicCategoriesRouteRoute._addFileChildren(
    publicCategoriesRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactUsRoute: ContactUsRouteWithChildren,
  LoginRoute: LoginRoute,
  publicCategoriesRouteRoute: publicCategoriesRouteRouteWithChildren,
  publicSearchRouteRoute: publicSearchRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
